apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: user-provided-service.se.tanzu.vmware.com.0.0.0
  annotations:
      capability.tanzu.vmware.com/provides: |
        [{ "name": "user-provided-service.se.tanzu.vmware.com",
          "displayName": "User Provided Service",
          "vendor": "VMware Tanzu SE Team",
          "description": "Provides service binding compatible object for services with externally managed lifecycles",
          "groupVersionKinds": [
            { "apiVersion": "services.se.tanzu.vmware.com/v1", "kind": "UserProvidedService" }
          ],
            "tags": ["Services & Data Services"]
        }]
spec:
  refName: user-provided-service.se.tanzu.vmware.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: user-provided-service.se.tanzu.vmware.com
spec:
  displayName: user-provided-service
  longDescription: user-provided-service.se.tanzu.vmware.com
  shortDescription: user-provided-service.se.tanzu.vmware.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: user-provided-service
spec:
  packageRef:
    refName: user-provided-service.se.tanzu.vmware.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: user-provided-service-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
